### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [showlab/sparseformer#1]
thank you for nice work.  I would greatly appreciate it if you could provide code examples that align with the functionality described in the paper.
❤️

**Comment by sebgao** [comment]
Hi, thank you for appreciating our work. We are reorganizing and cleaning up our code for better clarity, but this process may take some time as I am currently busy with coursework (final projects & exams.. :( ).

**Comment by TouqeerAhmad** [comment]
@sebgao any updates on this?

**Comment by sebgao** [comment]
@cenchaojun @TouqeerAhmad  now updated! The image SparseFormer code is now available. Please be patient for pre-trained models and video SparseFormer.

**Comment by cenchaojun** [comment]
> @cenchaojun @TouqeerAhmad now updated! The image SparseFormer code is now available. Please be patient for pre-trained models and video SparseFormer.

thank you~❤️
